carwash/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('carwashapp.urls'))
]

carwashapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from carwashapp.views import branch_listing, branch_detail_view, washers_view

urlpatterns = [
    path('', branch_listing, name='branches_listing'),
    path('detail/<int:pk>/', branch_detail_view),
    path("washer/<int:pk>", washers_view )
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carwashapp/models.py
from django.db import models
from datetime import datetime
from carwashapp.choises import GenderChoices, CarTypeChoices


class CompanyName(models.Model):
    title = models.CharField(max_length=225)

    def __str__(self):
        return self.title


class Branches(models.Model):
    city = models.CharField(max_length=225)
    location = models.CharField(max_length=225, unique=True, verbose_name="Address")
    number_of_boxes = models.PositiveSmallIntegerField(verbose_name="Number of boxes", default=1)
    car_wash_image = models.ImageField(upload_to='carwash_images')
    branch_employees = models.ManyToManyField(to='carwashapp.Employee', blank=False)

    class Meta:
        verbose_name = "Branch"
        verbose_name_plural = "Branches"

    def __str__(self):
        return self.location


class Employee(models.Model):
    full_name = models.CharField(max_length=225, verbose_name="Name and Lastname")
    employee_photo = models.ImageField(upload_to='employee_images')
    personal_number = models.CharField(max_length=11, verbose_name="Personal Number", unique=True)
    employee_status = models.BooleanField(default=True, verbose_name="Status")
    age = models.PositiveSmallIntegerField(verbose_name="Age")
    gender = models.PositiveSmallIntegerField("Gender", choices=GenderChoices.choices, default=GenderChoices.Male)
    hire_date = models.DateTimeField(verbose_name="Date",  default=datetime.now())
    share_amount = models.PositiveSmallIntegerField(verbose_name="Share",  default=1)

    class Meta:
        verbose_name = "Employee"
        verbose_name_plural = "Employees"

    def __str__(self):
        return self.full_name


class Prices(models.Model):
    car_type = models.PositiveSmallIntegerField("CarType", choices=CarTypeChoices.choices, default=CarTypeChoices.Sedan,
                                                unique=True)
    price = models.PositiveSmallIntegerField(verbose_name="Price")

    class Meta:
        verbose_name = "Price list"
        verbose_name_plural = "Price Lists"

    def __str__(self):
        return str(self.car_type)


class Discount(models.Model):
    prices = models.ManyToManyField(to='carwashapp.Prices', blank=False)
    discount = models.PositiveSmallIntegerField(verbose_name="discount", default=0)

    class Meta:
        verbose_name = "Discount"
        verbose_name_plural = "Discounts"

    def __str__(self):
        return f" Discount {self.discount}%"

    def prices_after_discount(self):
        discount_prices = []
        for price in self.prices.all():
            new_price = (price.price - (price.price * self.discount) / 100)
            if new_price % 1 == 0:
                discount_prices.append(int(new_price))
            else:
                discount_prices.append(new_price)
        return discount_prices


class Orders(models.Model):
    branch = models.ForeignKey(to="Branches", on_delete=models.PROTECT, null=False)
    car_type = models.PositiveSmallIntegerField("CarType", choices=CarTypeChoices.choices, default=CarTypeChoices.Sedan)
    price = models.ForeignKey('carwashapp.Prices', on_delete=models.PROTECT, null=False)
    car_number = models.CharField(max_length=7, null=False)
    washer = models.ForeignKey("carwashapp.Employee", on_delete=models.PROTECT, null=False)
    order_date = models.DateTimeField(default=datetime.now())
    washers_share = models.IntegerField(default=0)

    def __str__(self):
        return self.car_number

    def save(self, *args, **kwargs):
        self.washers_share = self.calculate_washers_share()
        super(Orders, self).save(*args, **kwargs)

    def calculate_washers_share(self):
        share_amount = (self.washer.share_amount * self.price.price) / 100
        return share_amount

carwashapp/views.py
from django.shortcuts import render, get_object_or_404
from datetime import datetime, timedelta
from carwashapp.models import Branches, CompanyName,  Discount, Orders


def branch_listing(request):
    branches = Branches.objects.all()
    disc = Discount.objects.all()
    name = CompanyName.objects.get()

    return render(request, "home.html", context={
        "branches": branches,
        "disc": disc,
        "name": name
    })


def branch_detail_view(request, pk):
    branch = get_object_or_404(Branches, pk=pk)
    emp = branch.branch_employees.all()

    return render(request, "detail.html", context={
        "branch": branch,
        "emp": emp
    })


def washers_view(request, pk):
    now = datetime.today()
    current_month = now.month
    current_year = now.year
    one_week_ago = datetime.today() - timedelta(days=7)
    order_per_washer_month = Orders.objects.all().filter(washer_id=pk, order_date__month=current_month)
    order_per_washer_week = Orders.objects.all().filter(washer_id=pk, order_date__gte=one_week_ago)
    order_per_washer_year = Orders.objects.all().filter(washer_id=pk, order_date__year=current_year)

    return render(request, "washer.html", context={
        "month": order_per_washer_month,
        "week": order_per_washer_week,
        "year": order_per_washer_year,
    })

carwashapp/templates/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'carwashapp/detail.css' %}">
</head>

<body>


<section>
    <img class="car-img" src="{{ branch.car_wash_image.url }}" alt="">


    <div class="details-div">
        <ul class="list">
            <li> City: {{ branch.city }}</li>
            <li> Address: {{ branch.location }}</li>
            <li> Boxes: {{ branch.number_of_boxes }}</li>

        </ul>
    </div>
</section>

<div class="employee">
    <h1>თანამშრომლები</h1>

    <ul>


        <li>
            {% for i in emp %}
                {% if i.employee_status %}
                    <a href="{{ request.get_full_path }}washer/{{i.id }}">
                    <img src="{{ i.employee_photo.url }}" alt="">
                    <span> Name: {{ i.full_name }}</span>
                    <span> Age: {{ i.age }}</span>
                    </a>
                {% endif %}
            {% endfor %}


        </li>

    </ul>

</div>


</body>
</html>

carwashapp/templates/home.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'carwashapp/home.css' %}">
</head>
<body>

    <div class="heading">
            <h1>{{ name }}</h1>
    </div>

    <div class="card-container">

        {% for i in branches %}
            <a href="/detail/{{ i.id }}">
                <div class="card">
                    <img src="{{ i.car_wash_image.url }}" alt="">
                    <p> City: {{ i.city }}</p>
                    <p> Address: {{ i.location }}</p>

                </div>
            </a>
        {% endfor %}

    </div>


    <section class="discounts">



{% for discs in disc %}
    <div>
    {% if disc%}
     <h2>ფასდაკლება</h2>
     <p>{{ discs.discount }} %</p>
    </div>
    {% endif %}

    <div class="new-prices">
    <div>
    {% for price in discs.prices_after_discount %}
        <p> ახალი ფასი: {{ price}}</p>
        {% endfor %}
    {% endfor %}
    </div>

<div>
    {% for prices in disc %}
        {% for p in prices.prices.all %}
            <p> მანქანის ტიპი: {{ p.get_car_type_display}}</p>
            {% endfor %}
    {% endfor %}
</div>
    </div>
    </section>
</body>
</html>

carwashapp/templates/washer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
      <link rel="stylesheet" href="{% static 'carwashapp/washer.css' %}">
</head>
<body>
<div>

<h1>გარეცხილი მანქანების სტატისტიკა</h1>

    <div class="statistics">
    <p> მიმდინარე კვირაში: {{ week.count }}</p>
     <p> მიმდინარე თვეში: {{ month.count }}</p>
    <p> მიმდინარე წელში:  {{ year.count }}</p>
    </div>
</div>
</body>
</html>